services:
  - type: web
    name: sf-backend
    env: node
    buildCommand: cd server && npm install && cp server.js package.json ../
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
